### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by coka** [nsoss/srce-desktop-app#10]
### Description
It's not very fun to work on a project where for every change we need to restart the application, or refresh the page. It would be nice to have everything update *automagically* whenever we save a file.
### Acceptance criteria
Configure the project so that a tool watches for file changes during development, keeping the open application window in sync with our code edits. **Hint:** We already have [Webpack](https://webpack.js.org/) set up, and Webpack [can make this happen](https://webpack.js.org/guides/hot-module-replacement).

**Comment by AleksandarVucenic** [comment]
This is maybe done, with new command in package.json (npm run dev command).

**Comment by coka** [comment]
OK. I'll double-check on Thursday. :+1:

**Comment by coka** [comment]
Closed by #27.
