### ISSUE TITLE
Set up database migrations

### ISSUE THREAD

**Issue by debeli** [nsoss/srce-desktop-app#14]
### Description
As we develop new features, we'll need to update the database schema. It would be useful to have an agreed-upon way to do this. Feel free to research what our options are for structuring schema updates.
### Acceptance criteria
Find a place in the application to wire up with the database, and write the initial migration for that data.

**Comment by coka** [comment]
@atanackoo21 Just for the sake of clarity:

For the first pass, we want a table called containing volunteers. Every volunteer should have a first name, last name, and timestamp when they were added. After that, we want to populate the volunteer selection form dropdown with real data from the database. For adding example volunteers, use a [seeder](https://sequelize.org/master/manual/migrations.html#creating-first-seed).
