### ISSUE TITLE
Basic navigation

### ISSUE THREAD

**Issue by coka** [nsoss/srce-desktop-app#3]
### Description
The application has 3 pages (views):
- "Dnevni". An overview containing a calendar, a list of calls, and buttons for call management.
- "Pojedinačni". A representation of a single call.
- "Pregled". Stats and charts for exploring call data.
### Acceptance criteria
For this issue, we need to create a navigation bar with buttons labeled "Dnevni", "Pojedinačni", and "Pregled". These buttons should take us to different pages. We should be able to go to any page from any other page. No need to worry about the contents of the pages themselves for now!

**Comment by AleksandarVucenic** [comment]
.
