### ISSUE TITLE
Initial overview page

### ISSUE THREAD

**Issue by coka** [nsoss/srce-desktop-app#4]
### Description
This is the main page of the application. It contains the following elements:
- Buttons for call management in the top left.
  - "Unos poziva"
  - "Brisanje poziva"
  - "Detalji poziva"
- A select box for the month. The options should be "Januar", "Februar", etc.
- A select box for the year. The options should be "2015", "2016", ..., "2019".
- A calendar widget in the top right, with the select boxes above it.
- A call list in the bottom half of the screen.
### Acceptance criteria
These elements should be laid out visually. Ping @amacanko for reference screenshots. The buttons don't need to do anything. The calendar and call list should only be placeholders, meaning that there can simply be a `<div>` with a colored background occupying the space where the element should be.

**Comment by AleksandarVucenic** [comment]
Want to do this!
