### ISSUE TITLE
Initial single call page

### ISSUE THREAD

**Issue by coka** [nsoss/srce-desktop-app#5]
### Description
This page contains a form for entering call data. Ping @amacanko to see what the current application looks like.

For the new application, we'll need slightly different fields:
- Poziv
  - r br poziva
  - vrsta kontakta*
  - datum poziva
  - dan
  - vreme poziva
  - trajanje poziva
  - vrsta poziva*
  - volonter*
- Pozivar
  - ime ili nadimak
  - pol*
  - starost*
  - bračno stanje*
  - koji put zove*
  - uključenost u plan*
- Opis razgovora
  - vrsta problema*
  - suicidni rizik*
  - suicidni faktor*
  - prethodni pokušaji suicida*
  - kratak sadržaj
  - napomena
- "Snimi", "Izmeni", "Kopiraj", "Prebaci u XLS", "Izađi"
>**Note:** An asterisk means that this field is a select box.
### Acceptance criteria
Create the layout described above. Everything should be interactive.

**Comment by AleksandarVucenic** [comment]
Want to do this also!

**Comment by coka** [comment]
Let's try to keep only 1 task "in progress" per person (because it's impossible to work on 2 at the same time :stuck_out_tongue:). Can @jelena1991 pick this one up?

**Comment by jelena1991** [comment]
Yes, I can.
