### ISSUE TITLE
Remove example volunteer

### ISSUE THREAD

**Issue by coka** [nsoss/srce-desktop-app#71]
Currently, whenever the app is launched with a fresh database, an example volunteer called "Marko Marin" with an ID of 55 is created. This was probably a stopgap solution to validate if the database is writeable. We should remove this.

**Comment by MLazarevic36** [comment]
Yesterday, I commented out the volunteer.findOne method that does it, don't want to delete it because I'm going to change functionality of it

**Comment by coka** [comment]
Alright, cool. :+1: Mark #67 as ready for review whenever you're comfortable with the changes you made. Moving this back to "In progress" for now.
