### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by coka** [nsoss/srce-desktop-app#9]
### Description
Any data we enter into the application will need to be stored somewhere. Since we'll be dealing with sensitive data, everything should be offline, and on the user's machine. [SQLite](https://sqlite.org/index.html) is the standard tool for local database storage. There might be a better tool out there. Feel free to suggest one in the comments! The requirements for the tool are:
- Available offline.
- Is in a single place (either a single file, or a single folder).
- Doesn't require the user to install any additional software.
- Doesn't occupy any network ports on the user's machine.
### Acceptance criteria
We need a script that will generate a new database for us for development purposes. Add a button to the application (anywhere), which will write "hello, world" to the database on every click.

**Comment by debeli** [comment]
So, we will go with:

- [sqlite3](https://www.sqlite.org/index.html) 
- [typeorm](https://typeorm.io/#/)

**Comment by coka** [comment]
@debeli Sounds good!

I tried to find a hip alternative to SQLite, but it looks like all other open source embedded databases are key-value stores, not relational stuff. Old, boring, and working tech seems like the way to go here. :stuck_out_tongue:

**Comment by debeli** [comment]
> ...  **and working tech** ...

See, you got that right :D
